FROM node:20 AS builder

WORKDIR /usr/src/app
COPY . ./
RUN npm install
RUN npx prisma generate
RUN npm run build

FROM node:20-alpine

WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/package.json ./package.json
RUN npm install --omit=dev
COPY --from=builder /usr/src/app/node_modules/.prisma ./node_modules/.prisma
COPY --from=builder /usr/src/app/node_modules/@prisma ./node_modules/@prisma
COPY --from=builder /usr/src/app/build ./build
COPY --from=builder /usr/src/app/public ./public
COPY --from=builder /usr/src/app/prisma ./prisma

HEALTHCHECK CMD curl -f http://localhost:3000/status || exit 1
EXPOSE 3000

CMD npx prisma migrate deploy && npm run start