FROM node:22.12 AS builder

WORKDIR /usr/src/app
COPY . ./
RUN npm install
RUN npx prisma generate
RUN npm run build

FROM node:22.12-alpine

WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/package.json ./package.json
RUN npm install --omit=dev
COPY --from=builder /usr/src/app/node_modules/.prisma ./node_modules/.prisma
COPY --from=builder /usr/src/app/node_modules/@prisma ./node_modules/@prisma
COPY --from=builder /usr/src/app/build/server ./build/server
COPY --from=builder /usr/src/app/build/client ./build/client
COPY --from=builder /usr/src/app/prisma ./prisma

HEALTHCHECK CMD wget --quiet --spider http://localhost:3000/status || exit 1
EXPOSE 3000

CMD npx prisma migrate deploy && npm run start