version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file: ../.env
    environment:
      DATABASE_URL: mysql://masaki:tsuji@db:3306/watch-duty-manager?schema=public
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0.27
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: watch-duty-manager
      MYSQL_USER: masaki
      MYSQL_PASSWORD: tsuji
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      
    
