name: Deploy to Host

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::559095527504:role/InfraStack-rolegithubcom440F6F02-JqKPE1g1hiC4
        aws-region: ap-northeast-1
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    
    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: watch-duty-manager
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f docker/Dockerfile .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: deploy
      uses: appleboy/ssh-action@v1.0.0
      env:
        IMAGE_TAG: ${{ github.sha }}
      with:
        host: chao.tokyo
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        envs: IMAGE_TAG
        script: |
          cd ~/watch-duty-manager
          aws ecr get-login-password --region ap-northeast-1 --profile watch-duty-manager-ecr-pull | docker login --username AWS --password-stdin 559095527504.dkr.ecr.ap-northeast-1.amazonaws.com
          docker compose -f docker/docker-compose.yml up -d --build app

