name: CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    uses: chao7150/actions/.github/workflows/ecr-push.yml@main
    secrets:
      aws_role_to_assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
    with:
      aws_region: ap-northeast-1
      ecr_repository: watch-duty-manager
      docker_file: container/Containerfile
