name: Deploy to Host

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH into the host and run commands
      run: |
        ssh chao@chao.tokyo -p 7150 "cd ~/watch-duty-manager && git pull origin main && docker compose -f docker/docker-compose.yml up -d --build app"
